In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.linear_model import Ridge, LinearRegression, Lasso

In [2]:
df = pd.read_csv('energydata_complete.csv')

In [3]:
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         19735 non-null  object
 1   Appliances   19735 non-null  int64
 2   lights       19735 non-null  int64
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9           19735 non-null  float64
 20  RH_9         19735 non-null  float64
 21  T_out        19735 non-null  float64
 22  Press_mm_hg  19735 non-null  float64
 23  RH_out       19735 non-null  float64
 24  Windspeed    19735 non-null  float64
 25  Visibility   19735 non-null  float64
 26  Tdewpoint    19735 non-null  float64
 27  rv1          19735 non-null  float64
 28  rv2          19735 non-null  float64
dtypes: float64(26), int64(2), object(1)
memory usage: 4.4+ MB

In [5]:
# Check for null values
df.isna().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [6]:
# Question 12

x = df['T2'].values.reshape(-1,1)
y = df['T6'].values.reshape(-1,1)

x_train,x_test,y_train,y_test= train_test_split(x, y, test_size=0.3, random_state=42)

# linear regression training on x and y
lin_reg=LinearRegression()
lin_reg.fit(x_train,y_train)
predicts =lin_reg.predict(x_test)

# r_square 
from sklearn.metrics import r2_score
r_squared=r2_score(y_test, predicts)
round(r_squared, 2)

0.64

In [7]:
# dropping date and lights column from the dataset

df.drop(['date', 'lights'], axis = 1, inplace = True)

In [8]:
# Normalise the dataset using MinMaxScaler class

scaler = MinMaxScaler()

normalised_df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
target_df = normalised_df['Appliances']
features_df = normalised_df.drop('Appliances', axis=1)

In [9]:
# Splitting the dataset(70-30) in to training and testing datasets

x_train, x_test, y_train, y_test = train_test_split(features_df, target_df, test_size=0.3, random_state=42)
linear_model = LinearRegression()

# fit the model to the training dataset
linear_model.fit(x_train, y_train)

# obtain predictions
predicted_values = linear_model.predict(x_test)

In [10]:
# Question 13

# Mean Square Error(MAE)
mean_a_err = mean_absolute_error(y_test, predicted_values)
round(mean_a_err, 2)

0.05

In [11]:
# Question 14

# Residual Sum Squares(RSS) 
rss = np.sum(np.square(y_test - predicted_values))
round(rss, 2)

45.35

In [12]:
# Question 15

# Root mean Squared Error(RMSE)
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 3)

0.088

In [13]:
# Question 16

#Co-efficient of determination(R_squared)
r2_score = r2_score(y_test, predicted_values)
round(r2_score, 2)

0.15

In [14]:
# Question 20

# Lasso training
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)

predict_lasso = lasso_reg.predict(x_test)
#RMSE after lasso 
rmse_lasso = np.sqrt(mean_squared_error(y_test, predict_lasso))
round(rmse_lasso, 3)

0.094

In [15]:
# train ridge model

ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)

#predict ridge
predicted_ridge_values = ridge_reg.predict(x_test)

In [16]:
# Question 19
# Let's compare the effects of regularisation

def get_weights_df(model, feat, col_name):
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df

linear_model_weights = get_weights_df(linear_model, x_train,'Linear_Model_Weight')
ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge Weight')
lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')

final_weights = pd.merge(linear_model_weights, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on='Features')
final_weights

       Features  Linear_Model_Weight  Ridge Weight  Lasso_weight
0          RH_2            -0.456698     -0.411071     -0.000000
1         T_out            -0.321860     -0.262172      0.000000
2            T2            -0.236178     -0.201397      0.000000
3            T9            -0.189941     -0.188916     -0.000000
4          RH_8            -0.157595     -0.156830     -0.000110
5        RH_out            -0.077671     -0.054724     -0.049557
6          RH_7            -0.044614     -0.045977     -0.000000
7          RH_9            -0.039800     -0.041367     -0.000000
8            T5            -0.015657     -0.019853     -0.000000
9            T1            -0.003281     -0.018406      0.000000
10          rv2             0.000770      0.000748     -0.000000
11          rv1             0.000770      0.000748     -0.000000
12  Press_mm_hg             0.006839      0.006584     -0.000000
13           T7             0.010319      0.010098     -0.000000
14   Visibility             0.012307      0.012076      0.000000
15         RH_5             0.016006      0.016152      0.000000
16         RH_4             0.026386      0.024579      0.000000
17           T4             0.028981      0.027384     -0.000000
18    Windspeed             0.029183      0.030268      0.002912
19         RH_6             0.038049      0.035519     -0.000000
20         RH_3             0.096048      0.095135      0.000000
21           T8             0.101995      0.101028      0.000000
22    Tdewpoint             0.117758      0.083128      0.000000
23           T6             0.236425      0.217292      0.000000
24           T3             0.290627      0.288087      0.000000
25         RH_1             0.553547      0.519525      0.017880

From the results above, only 4 features are with non-zero weights

In [17]:
# Question 17

# Query lowest and highest weights
lowest_and_highest = get_weights_df(linear_model,x_train,'Linear model').sort_values(by=['Linear model'],ascending=True)
lowest_and_highest

       Features  Linear model
0          RH_2     -0.456698
1         T_out     -0.321860
2            T2     -0.236178
3            T9     -0.189941
4          RH_8     -0.157595
5        RH_out     -0.077671
6          RH_7     -0.044614
7          RH_9     -0.039800
8            T5     -0.015657
9            T1     -0.003281
10          rv2      0.000770
11          rv1      0.000770
12  Press_mm_hg      0.006839
13           T7      0.010319
14   Visibility      0.012307
15         RH_5      0.016006
16         RH_4      0.026386
17           T4      0.028981
18    Windspeed      0.029183
19         RH_6      0.038049
20         RH_3      0.096048
21           T8      0.101995
22    Tdewpoint      0.117758
23           T6      0.236425
24           T3      0.290627
25         RH_1      0.553547

Hence RH2 and RH_1 are features with lowest and highest weights

In [18]:
# Question 18

# RMSE after ridge regression test
rmse_ridge = np.sqrt(mean_squared_error(y_test, predicted_ridge_values))
round(rmse_ridge, 3)

0.088